name: Download and update contributions-pro-fr.csv

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  download_and_commit:
    runs-on: ubuntu-latest
    # container: 
    #   image: morglum/dons_elections

    steps:
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.1.3'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev
        Rscript -e 'install.packages(c("httr", "lubridate", "dplyr", "janitor", "stringr", "readr"))'

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.MYGITHUBPAT }}
        persist-credentials: false

    - name: Download and rename CSV
      run: Rscript download_and_rename.R

    - name: Commit changes
      run: |
        git config --global user.email "simoncoulombe@gmail.com"
        git config --global user.name "simon coulombe"
        git remote set-url origin "https://x-access-token:${{ secrets.MYGITHUBPAT }}@github.com/SimonCoulombe/dons_elections_qc.git"
        git add data/*
        git commit -m "Automated update of contributions-pro-fr.csv"
        git push origin HEAD:master