name: Download and update contributions-pro-fr.csv

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  download_and_commit:
    runs-on: ubuntu-latest
    container:
      image: docker://morglum/dons_elections:latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

#    - name: Set up R environment
#      run: |
#        Rscript -e 'install.packages("httr")'
#        Rscript -e 'install.packages("lubridate")'

    - name: Download and rename CSV
      run: Rscript download_and_rename.R

    - name: Commit changes
      run: |
        git config --local user.email "<YOUR_EMAIL>"
        git config --local user.name "<YOUR_NAME>"
        git add data/*
        git commit -m "Update contributions-pro-fr.csv"
        git push
