name: Download and update contributions-pro-fr.csv

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  download_and_commit:
    runs-on: ubuntu-latest

    steps:
    - name: Set up R
      uses: r-lib/actions/setup-r@v1

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev
        Rscript -e 'install.packages(c("httr", "lubridate"))'

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.MYGITHUBPAT }}
        persist-credentials: false

    - name: Download and rename CSV
      run: Rscript download_and_rename.R

    - name: Commit changes
      run: |
        git config --global user.email "simoncoulombe@gmail.com"
        git config --global user.name "simon coulombe"
        git add data/*
        git commit -m "Update contributions-pro-fr.csv"
        git push origin HEAD:master
