name: generate cumulatifs

on:
  schedule:
    - cron: '10 8 * * *'
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest
    container: 
      image: morglum/dons_elections
    env:
      perroquetdejeff_api_key: ${{ secrets.perroquetdejeff_api_key }}
      perroquetdejeff_api_secret_key: ${{ secrets.perroquetdejeff_api_secret_key }}
      perroquetdejeff_access_token: ${{ secrets.perroquetdejeff_access_token }}
      perroquetdejeff_access_token_secret: ${{ secrets.perroquetdejeff_access_token_secret }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.MYGITHUBPAT }}
        persist-credentials: false

    - name: Update repository ownership
      run: chown -R $(whoami) . || true

    - name: tweet
      run: Rscript tweet.R

    - name: Commit changes
      run: |
        git config --global user.email "simoncoulombe@gmail.com"
        git config --global user.name "simon coulombe"
        git remote set-url origin "https://x-access-token:${{ secrets.MYGITHUBPAT }}@github.com/SimonCoulombe/dons_elections_qc.git"
        git add data/*
        git commit -m "Automated update of tweet and myplot.png"
        git push origin HEAD:master
